//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBASAWAPP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CONTACTO
    {
        public int IDCONTACTO { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NOMBRE { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Telefono")]
        public string TELEFONO { get; set; }

        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string CORREO { get; set; }

        [Required]
        [Display(Name = "Mensaje")]
        public string MENSAJE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
