//------------------------------------------------------------------------------
// <auto-generated>
<<<<<<< HEAD
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
=======
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
>>>>>>> dffb64aa45d71c5ad356341c53f2e15f67389289
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBASAWAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public int IDFACTURA { get; set; }
        public string IDUSUARIO { get; set; }
        public System.DateTime FECHA { get; set; }
        public float IVA { get; set; }
        public float TOTAL { get; set; }
        public int NUMPAGO { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
    }
}
