//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBASAWAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY
    {
        public int IDHISTORY { get; set; }
        public Nullable<int> IDPRODUCT { get; set; }
        public string IDUSER { get; set; }
        public System.DateTime FECHAHISTORY { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
