//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBASAWAPP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class INSTALADOR
    {

        public int IdRol { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string PROVINCIA { get; set; }
    
        public virtual PROVINCIA PROVINCIA1 { get; set; }
    }
}
