//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBASAWAPP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.HISTORies = new HashSet<HISTORY>();
            this.PRODUCTSPS = new HashSet<PRODUCTSP>();
            this.QUOTECARTs = new HashSet<QUOTECART>();
        }

        public int ID { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NAME { get; set; }

        [Required]
        [Display(Name = "Descripcion")]
        public string DESCRIPTION { get; set; }

        [Required]
        [Display(Name = "Precio")]
        public decimal PRICE { get; set; }
        public string URL { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    
        public virtual CATEGORy CATEGORy1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORY> HISTORies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTSP> PRODUCTSPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUOTECART> QUOTECARTs { get; set; }
    }
}
