//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBASAWAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTSPS
    {
        public int ID_SALE { get; set; }
        public int ID_PRODUCT { get; set; }
        public int QUANTITY { get; set; }
    
        public virtual PRODUCT PRODUCTS { get; set; }
        public virtual SALES SALES { get; set; }
    }
}
