//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBASAWAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUOTECART
    {
        public int ID { get; set; }
        public string ID_USER { get; set; }
        public Nullable<int> ID_PRODUCT { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string RESULTADO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
