//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBASAWAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOPP_CART
    {
        public string ID_USER { get; set; }
        public Nullable<int> ID_PRODUCT { get; set; }
        public int QUANTITY { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual PRODUCTS PRODUCTS { get; set; }
    }
}
